modules/*/config/view.yml:
  class:    saViewConfigHandler
  file:     %SF_LIB_DIR%/config/saViewConfigHandler.class.php

config/routing.yml:
  class:    saRoutingConfigHandler
  file:     %SF_LIB_DIR%/config/saRoutingConfigHandler.class.php
