rendering: ~

cache_control:
  class: saCacheControlFilter

enable_app:
  class: saCheckEnabledApplicationFilter

xrds_header:
  class: saAppendXRDSHeaderFilter

security:  ~

emoji:
  class: saEmojiFilter

cache:     ~

execution:
  class: saExecutionFilter
  param:
    type: execution
