rendering: ~

cache_control:
  class: saCacheControlFilter

enable_app:
  class: saCheckEnabledApplicationFilter
  param:
    app: mobile

security:  ~

deny:
  class: sfDenyFromNonMobileFilter

io:
  class: sfMobileIOFilter

emoji:
  class: saEmojiFilter

cache:     ~

execution:
  class: saExecutionFilter
  param:
    type: execution
