options:
  charset: utf8
actAs: [Timestampable]

Member:
  actAs: [Timestampable, saActivateBehavior]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    name: { type: string(64), default: "", notnull: true, comment: "Nickname" }
    invite_member_id: { type: integer(4), comment: "Member id of the person who invited this member" }
    is_login_rejected: { type: boolean, notnull: true, default: false, comment: "Rejected member" }
  relations:
    Member: { local: invite_member_id, foreign: id, onDelete: set null }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves informations of members"

MemberImage:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    member_id: { type: integer(4), notnull: true, comment: "Member id" }
    file_id: { type: integer(4), notnull: true, comment: "Image file id in the ''file'' table" }
    is_primary: { type: boolean, comment: "This is primary" }
  relations:
    Member: { local: member_id, foreign: id, onDelete: cascade }
    File: { local: file_id, foreign: id, onDelete: cascade }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves images in member profiles"

File:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    name: { type: string(64), default: "", notnull: true, comment: "File name" }
    type: { type: string(64), default: "", notnull: true, comment: "Type of this file" }
    filesize: { type: integer(4), default: 0, notnull: true, comment: "File size" }
    original_filename: { type: string, comment: "Original filename" }
  indexes:
    name_UNIQUE:
      fields: [name]
      type: unique
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves informations of files uploaded"

FileBin:
  columns:
    file_id: { type: integer(4), primary: true, comment: "File id" }
    bin: { type: blob, comment: "Content of file" }
  relations:
    File: { local: file_id, foreign: id, onDelete: cascade, foreignType: one, owningSide: true }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves content of files"

AdminUser:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    username: { type: string(64), default: "", notnull: true, comment: "Administrator''s username" }
    password: { type: string(40), default: "", notnull: true, comment: "Administrator''s password" }
  indexes:
    username_UNIQUE:
      fields: [username]
      type: unique
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves informations to login administration page"

SiteConfig:
  actAs: []
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    name: { type: string(64), default: "", notnull: true, comment: "Configuration name" }
    value: { type: string, comment: "Configuration value" }
  indexes:
    name_UNIQUE:
      fields: [name]
      type: unique
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves configurations of this SNS"

MemberConfig:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    member_id: { type: integer(4), notnull: true, comment: "Member id" }
    name: { type: string(64), default: "", notnull: true, comment: "Configuration name" }
    value: { type: string, default: "", notnull: true, comment: "Configuration value" }
    value_datetime: { type: timestamp, comment: "Configuration datetime value" }
    name_value_hash: { type: string(32), notnull: true, comment: "Hash value for searching name & value" }
  relations:
    Member: { local: member_id, foreign: id, onDelete: cascade }
  indexes:
    name_INDEX:
      fields: [name]
    name_value_hash_INDEX:
      fields: [name_value_hash]
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves configurations of each members"

Session:
  actAs: []
  columns:
    id: { type: string(128), primary: true }
    session_data: { type: string, comment: "Session information" }
    time: { type: string, comment: "Timestamp of generated time" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves session data"

Plugin:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "Serial number" }
    name: { type: string(64), default: "", notnull: true, comment: "Nickname" }
    is_enabled: { type: boolean, default: true, notnull: true, comment: "Notification Enabled" }
  indexes:
    is_enabled_INDEX:
      fields: [is_enabled]
    name_UNIQUE:
      fields: [name]
      type: unique
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "Saves informations of plugins"
