member_add_image:
  url: m
  class: saMailRoute
  param: { module: member, action: image }

community_add_image:
  url: c.:id
  class: saMailRoute
  param: { module: community, action: image }
  required: { id: \d+ }
